account:
  replicaCount: as required
  name: deployment
  image:
    repository: #########.dkr.ecr.me-south-1.amazonaws.com/account (docker image path )
    tag: 2

  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

  envType: "1"

  service:
    name: service
    containerPort: 80

  ingress: 
     name: "ingress"
     enabled: true
     className: "nginx"
     sslRedirect: "true"
     useRegex: "true"
     rewriteTarget: "/$1"
     hosts:
        host: "example.com"
        path: "/(.*)"
