apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.account.service.name }}
spec:
  selector:
    app: {{ .Values.account.name }}
  type: 
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.account.service.containerPort }}